http_server:
    address: ":9000"
    read_timeout: 10s
    write_timeout: 10s
    idle_timeout: 60s

storage:
    port: "5432"
    user: postgres
    db_name: postgres
    host: postgres

pending_time_in_seconds: 180
check_interval: 5s
close_server_time: 15s
close_service_time: 5s
